name: SRP2
on:
  schedule:
   
    # Run at 00:00 and 00:10 UTC
    - cron: '0,10 0 * * *'
    # Run every 10 minutes starting at 00:01 to 01:59 UTC
    - cron: '01/10 0-1 * * *'
    # Run at 02:00, 02:10, 02:20, and 02:30 UTC
    - cron: '0,10,20,30 2 * * *'

  
jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Set up Maven
        run: |
          sudo apt-get install -y maven
          
      - name: Build with Maven
        run: |
          mvn test
